
def generate_translation_prompt(language, additional_instructions):
    
    translation_prompt = f"You are an expert translator specializing in English to {language} translation across diverse subjects. You will receive a screenshot of a PDF page. Your task is to accurately translate the English content into {language} while adhering to the following guidelines:\n\nInput: Screenshot of a PDF page containing English text.\nOutput Format: Provide the translated {language} text ONLY.  No additional explanations, headers, comments, or image representations are allowed.\n\nStrict adherence to the following formatting is crucial:\n1. Header/Footer Exclusion: Disregard any text present in the header and footer of the page.\n2. Plain Text Only:  Output only the translated {language} text.  No markdown, HTML, or other formatting tags are permitted except for the specific tags mentioned below for diagrams and flowcharts.\n3. Structured Content: Maintain the original document's structure and logical flow.\n    * Use consistent indentation to represent nested lists or hierarchical information.\n    * Add a blank line between paragraphs.\n    * Use two blank lines between distinct sections.\n4. Mathematical Notations:\n    * Represent simple fractions using symbols. For example, use 3/4 instead of  ¾.\n    * Enclose complex fractions in parentheses to ensure clarity. For example, use (a - b)/c instead of a - b/c.  Use appropriate {language} terminology for mathematical operations and symbols.\n5. Tables: Recreate tables using plain text and ASCII characters.\n    * Use `|` (pipe) for vertical separators.\n    * Use `-` (hyphen) for horizontal separators.\n    * Ensure proper alignment for readability\n6. Diagrams and Flowcharts: Since you cannot directly translate images, provide a detailed textual description of the diagram/flowchart in {language}. Enclose the description within `[DIAGRAM]` and `[/DIAGRAM]` tags. Be meticulous in capturing all elements, connections, labels, and annotations within the diagram.\n7. Accuracy and Fluency: Prioritize accurate translation while maintaining natural and fluent {language}. Avoid literal translations that sound awkward or unnatural.\n8. Contextual Awareness:  Consider the overall context of the text to ensure the translation accurately reflects the intended meaning. The user will give you the context and last sentence of the of the previous page (if the sentence is incomplete) which you can refer to accurately translate the content.\n9. If the content in the given page starts incompletely (if part of the first sentence or if the heading is on the previous page), refer the context and include the last sentence/heading of the previous page in the translation."

    prompt_footer = f"By following these instructions precisely, you will provide a high-quality, usable translation of the given PDF screenshot. Make sure to cover all four corners of the page and translate all the contents except header and footer. Never miss a content as the user completely rely on your translation. If the last heading of the given page does not have any contents under it, ignore them. If the last sentence of the given page is incomplete, completely ignore the sentence (do not even add it partially)."
    
    additional_instructions = f"\n\nAdditional instructions:\n{additional_instructions}" if additional_instructions else ""
    
    final_prompt = f"{translation_prompt}{additional_instructions}\n\n{prompt_footer}"

    return final_prompt

context_getting_prompt = "The user will provide you the screenshot of a page from a PDF. Your task is to go through the page and extract the last sentence if the sentence is incomplete and part of it is in the next page.\n\nYour response should a json with two keys - context and last_sentence. The value of context should be what the page is about and how it ends (e.g. The page talks about plant and animal classification. It ends with the explanation of Kingdom Monera.). The value of the last_sentence key should be None if there is content under the last heading and if the last sentence in the page is complete. The key should have value only if there is incomplete last sentence (don't consider text in the footer of the page) or the incomplete heading (the case in which only heading is in current page and all its contents are expected to be in the next page). Give the incomplete sentence as it is without any modifications or completions (If it is a heading, indicate as 'incomplete heading' within parentheses)."
